### ISSUE TITLE
Cannot fetch ascli package

### ISSUE THREAD

**Issue by ganigeorgiev** [hiqdev/asset-packagist#101]
One of my dependencies requires the `ascli` package (https://www.npmjs.com/package/ascli), and I've tried fetching it through the asset-packagist website but got "Package update failed" error.

This is the error that is returned on composer install/update:
```
Problem 1
    - npm-asset/protobufjs 5.0.3 requires npm-asset/ascli ~1 -> no matching package found.
    ...
```

The main package I'm trying to install is `npm-asset/presentator-spa` (https://www.npmjs.com/package/presentator-spa).

**Comment by SilverFire** [comment]
Hi, thank you for the report.

The package author uses `repository.type = 'url'` that is is not commonly used. I have opened a PR in [fxp/c-a-p](https://github.com/fxpio/composer-asset-plugin/pull/331) but I'm not sure it will be merged.

Though I've fetched that package for you, I recommend you to submit a PR to `ascli` repository to fix this thing as well.

**Comment by SilverFire** [comment]
Happily, https://github.com/fxpio/composer-asset-plugin/pull/331 was merged
