### ISSUE TITLE
Malformed JSON

### ISSUE THREAD

**Issue by NickWilde1990** [hiqdev/asset-packagist#102]
### Please provide your `composer.json` if appropriate.
Composer is failing and if I open the relevant url "https://asset-packagist.org/p/provider-latest/76bb9c4859328409ef739e3588f85aa03d483532e391963f2b88455371142762.json" then Firefox says "SyntaxError: JSON.parse: unterminated string at line 1 column 130812 of the JSON data".
Was working fine this morning.

**Comment by patrickcate** [comment]
Started getting what I think is a similar error yesterday:

`[Seld\JsonLint\ParsingException]                                                                                        
  "/home/vagrant/.composer/cache/repo/https---asset-packagist.org/p/provider-latest/.json" does not contain valid JSON    
  Parse error on line 1:                                                                                                  
  ...t/moment-timezone":{"sha2                                                                                            
  ----------------------^                                                                                                 
  Invalid string, it appears you forgot to terminate a string, or attempted to write a multiline string which is invalid                                                                                                                            
`
Clearing the composer cache didn't help.

**Comment by SilverFire** [comment]
Hello, @NickWilde1990!

```
#> curl https://asset-packagist.org/p/provider-latest/76bb9c4859328409ef739e3588f85aa03d483532e391963f2b88455371142762.json | jq type
"object"
```

It seems to work, at least now. Do you experience a problem?

**Comment by marcoliverteschke** [comment]
Hello @SilverFire,
I'm experiencing the same problem right now at this address:

https://asset-packagist.org/p/provider-latest/3605882fb141c001814ca5155dcd729e6a7a35feb459940fce937d914ae57329.json

**Comment by hiqsol** [comment]
Server-side problems. Should be ok now.

**Comment by bkosborne** [comment]
I'm getting these errors. See #105

**Comment by SilverFire** [comment]
Fixed, sorry for the inconveniences!
