### ISSUE TITLE
Compatibility with Composer 2.0

### ISSUE THREAD

**Issue by freezy-sk** [hiqdev/asset-packagist#103]
Composer 2.0 will not allow package names with more than one consecutive dash/dot/underscore
What to do with packages named like this `npm-asset/fullcalendar--core`?

Current deprecation warning from composer
`Deprecation warning: require.npm-asset/fullcalendar--core is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.`

**Comment by hiqsol** [comment]
We just follow fxp composer-asset-plugin agreement for npm vendor separator.
So let's see first what fxp maintainers will do :)

**Comment by schmunk42** [comment]
@hiqsol Is there an issue in the fxp repo or composer/composer.

@samdark @cebe This could cause big issues with Yii 2.x

**Comment by liborm85** [comment]
Created issue https://github.com/fxpio/composer-asset-plugin/issues/333

**Comment by rodrigoaguilera** [comment]
Can we keep this open for tracking?

I don't stale bots because they make me write this kind of comment 😉

**Comment by schmunk42** [comment]
Stalebot should be configured in a way that they only mark issues as stale, when there was a manual tag "awaiting feedback" or similar. This is such a pain.

**Comment by hiqsol** [comment]
Ok, I've removed that workflow.

**Comment by filsh** [comment]
Is there any progress to solve the problem?

**Comment by schmunk42** [comment]
I don't think it can be solved, you'd have to convince the composer devs to allow  two dashes in the name`--`, which is highly unlikely IMHO.

You can stick with composer `<2.0`, but you still will get errors from packagist.

**Comment by liborm85** [comment]
@schmunk42 In issue https://github.com/fxpio/composer-asset-plugin/issues/333 proposes @francoispluchino  change from `--` to `-slash-`. If both variants were supported we will avoid backward compatibility issues.

**Comment by schmunk42** [comment]
I think the problem is, that all existing packages use `--` and composer might not allow that at all.

**Comment by cebe** [comment]
I made an issue on composer repo to discuss this: https://github.com/composer/composer/issues/8749

**Comment by cebe** [comment]
> you'd have to convince the composer devs to allow two dashes in the name`--`, which is highly unlikely IMHO.

seems you just have to ask ;) solved: https://github.com/composer/composer/pull/8767

**Comment by schmunk42** [comment]
> > you'd have to convince the composer devs to allow two dashes in the name`--`, which is highly unlikely IMHO.
> 
> seems you just have to ask ;) solved: [composer/composer#8767](https://github.com/composer/composer/pull/8767)

Honestly, I did not believe that this would happen. But very nice :+1:

**Comment by cebe** [comment]
> Honestly, I did not believe that this would happen. But very nice +1

me neither, but that is no reason not to try :smiley:

**Comment by hiqsol** [comment]
Wow! Just wow :) Congrats everybody!

**Comment by freezy-sk** [comment]
@cebe thank you. I will close this issue when that fix will be released
