### ISSUE TITLE
TransportException file not found

### ISSUE THREAD

**Issue by kporras07** [hiqdev/asset-packagist#106]
Hi there,

I'm having issues like this in my CI. Is this somehow related to yesterday's issues with storage? Is it possible to workaround it?

```
[Composer\Downloader\TransportException]                                                                                                                                          
  The "https://asset-packagist.org/p/npm-asset/byline/920da2ad7002a68fa527d3d93088f3a7484ba8e264f0a9d08789092bb8f6e3b7.json" file could not be downloaded (HTTP/1.1 404 Not Found)  
```

It sometimes change to querystring or querystring-es3 but the error is the same; the hash provided by provider-latest can't be fetched.

Any ideas/help?                                                                                                  

Thanks,

**Comment by socialnicheguru** [comment]
https://github.com/composer/packagist/issues/1042
I am getting the same with random packages. 

 I run "composer update" package files are not found. And it is not the same package.
<img width="1332" alt="Screen Shot 2019-10-28 at 9 52 47 AM" src="https://user-images.githubusercontent.com/172735/67797213-aa161100-fa3e-11e9-8b18-801de4854385.png">

I run composer clearcache and then composer update again and I get the same thing.

When I take a look at the packages there are so many where Commit SHA is not defined. 
<img width="1257" alt="Screen Shot 2019-10-29 at 7 47 45 AM" src="https://user-images.githubusercontent.com/172735/67797188-a2ef0300-fa3e-11e9-853a-d48e4ed66e7c.png">

**Comment by tigrasti** [comment]
Same here

**Comment by socialnicheguru** [comment]
also the unrecognized packages seem to change

**Comment by jasonhuvl** [comment]
Same issue

`  [Composer\Downloader\TransportException]                                                                                                                                                        
  The "https://asset-packagist.org/p/npm-asset/require-package-name/f7efe92420d1470aa98a5741f575405edf8092217762c6e33972c234d381d0e6.json" file could not be downloaded (HTTP/1.1 404 Not Found)`

**Comment by socialnicheguru** [comment]
now i get this and I cannot find "npm-asset/randy.js"

[Composer\Downloader\TransportException]                                                                          
  The "https://asset-packagist.org/p/npm-asset/randy.js/a32c86adb58411baee0944e539085d45fb8ae8489c7fe8fbdb2b5991b7  
  407b60.json" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by SilverFire** [comment]
We are running full packages upgrade, all packages that are not available now will be loaded&updated during the next few hours.

I will keep you updated, guys.

**Comment by rodrigoaguilera** [comment]
I just want to say thank you for the service you offer for free to the community. Please take the time is necessary to fix the issues.

**Comment by kporras07** [comment]
Yep, thank you very much for all the hard work :D

**Comment by SilverFire** [comment]
No way... 

![image](https://user-images.githubusercontent.com/4499203/67920675-c4223180-fbad-11e9-892b-5b91c37360cf.png)

```
139G    ./git-github.com-DefinitelyTyped-DefinitelyTyped.git
```

I could not imagine such a huge repo could be cloned.

**Comment by SilverFire** [comment]
Gave a detailed reply to a neighbor issue. Please, check it out: https://github.com/hiqdev/asset-packagist/issues/105#issuecomment-548221699

**Comment by SilverFire** [comment]
Closing this issue for now. Thanks!

**Comment by Thanty** [comment]
@SilverFire I'm really sorry but problem still exists.

`
[Composer\Repository\RepositorySecurityException]
The contents of https://asset-packagist.org/p/npm-asset/get-imports/67f5d292c49a427cdc355a26cc8207353282752447ba2ebfa474769aad1cdf18.json do not match its signature. This could indicate a man-in-the-middle attack or e.g. antivirus software corrupting files. Try running composer again and report this if you think it is a mistake.
`

Fetching all used repositories didn't help.

**Comment by socialnicheguru** [comment]
Please allow others to confirm before closing. This is not fixed. 
There are two issues: content mismatch which I do believe was fixed (and was not my issue in the first place).

The other is missing packages which is still going on. I will open another issue to make sure that it gets the attention it deserves

**Comment by SilverFire** [comment]
Moving discussion to #108
