### ISSUE TITLE
"Contents do not match its signature" (zero-length JSON)

### ISSUE THREAD

**Issue by joshkel** [hiqdev/asset-packagist#109]
I'm getting errors when trying to use Composer to install packages (even non-Asset Packagist packages) with Asset Packagist enabled:

> The contents of https://asset-packagist.org/p/npm-asset/expected/bf82a28feae5961b052c3d5a5a2135094a55ee0e659dc78a9fb7f6344efc7bd7.json do not match its signature. This could indicate a man-in-the-middle attack or e.g. antivirus software corrupting files. Try running composer again and report this if you think it is a mistake.

If I manually download that file, I can see that it has zero length.

I wondered if this has the same cause as #105 - although the specific error is different, and that says it's fixed, so I'm not certain.

Thank you.

**Comment by SilverFire** [comment]
Yes, it's related to issue #105 
Your issue duplicates #108 so I'm closing it
