### ISSUE TITLE
Content-Length mismatch

### ISSUE THREAD

**Issue by petk** [hiqdev/asset-packagist#110]
### Please provide your `composer.json` if appropriate.

This is related to #104 

With composer installation this error happens:

```
 [Composer\Downloader\TransportException]                                   
  Content-Length mismatch, received 98048 bytes out of the expected 4187858  
```

Problematic file:
https://asset-packagist.org/p/provider-latest/5fde9abd83042362944d7d07d5b78d6a2e8073fc0828575345ca2effe6498e7c.json

Thank you.

**Comment by robertshell22** [comment]
I am also experiencing this.

**Comment by SilverFire** [comment]
I've purchased additional 200G and again this repo took it all:

```
199G    ./git-github.com-DefinitelyTyped-DefinitelyTyped.git
```

I check that the repo has hundreds of files like this `git-github.com-DefinitelyTyped-DefinitelyTyped.git/objects/pack/tmp_pack_BOub0W`, around 1GB each. Thanks to [stackoverflow](https://stackoverflow.com/questions/40938591/git-fetch-fills-disk-with-tmp-pack-files-never-completes), found that these files start piling up when the repository can't get fully cloned.

A worker that clones repos has a time limit of 10 minutes, so the download has been interrupted a lot of times, taking all the available space on the disk. I have cloned this repository manually and hope it will never pop up.

@petk @robertshell22 could you check now, please?

**Comment by SeanAFOPIN** [comment]
Hi, I was also experiencing this issue and it seems to be resolved now.  
Thank you for the quick turnaround!

**Comment by petk** [comment]
Wow, 200GB. And for one package... Amazing. Thank you so much for fixing this abnormality so soon. It seems to be working ok now.
