### ISSUE TITLE
How could I composer require npm-asset/xxx without the dependencies

### ISSUE THREAD

**Issue by whatcq** [hiqdev/asset-packagist#111]
I have search a lot,but haven't find solved approach.

Because we require the npm-asset just for using,not for debug or editable.
We can download less packages, save time and space!
So I want to `composer require npm-asset/admin-lte`  without the dependencies under it.
How could I skip/ignore package.json?
Or is there a param for this requirement?

thx.

**Comment by whatcq** [comment]
I have to use composer replace+conflict to skip the dependencies.
@see cebe/assetfree-yii2

**Comment by hiqsol** [comment]
This package is available directly at packagist: 

https://packagist.org/packages/almasaeed2010/adminlte

You can use it directly without asset-packagist

**Comment by whatcq** [comment]
What about other packages?The question is still there.

thanks @hiqsol , it works for admin-lte.

**Comment by hiqsol** [comment]
> What about other packages? The question is still there

Unfortunately, I don't see an easy solution inside of Asset Packagist.

The best solution would be to add the package in question to the Packagist :)

**Comment by whatcq** [comment]
Ok,I see.
Thank you again.
