### ISSUE TITLE
Error while searching

### ISSUE THREAD

**Issue by nadar** [hiqdev/asset-packagist#116]
I just encountered this error while searching for a certain package:

![image](https://user-images.githubusercontent.com/3417221/76973818-bb4db480-6930-11ea-87cd-bc532a59126d.png)

cause when i try to install this packge, its not found :-)

```
The requested package bower-asset/ui-cropper could not be found in any version, there may be a typo in the package name
``` 

so i decide to check whether this library exists or not.

**Comment by hiqsol** [comment]
That was a temporary problem of libraries.io service that we use to search for packages.
It works fine now.

I've fetched the package and it should work now.

**Comment by srjosh** [comment]
This error is recurring.
