### ISSUE TITLE
Link to npm packages with vendor name are not working

### ISSUE THREAD

**Issue by cebe** [hiqdev/asset-packagist#117]
While researching about issue #103, I found that links to npm are wrong for packages that have a vendor prefix, e.g.

https://asset-packagist.org/package/npm-asset/claviska--jquery-minicolors

The "see on Npm" link is `https://npmjs.com/package/claviska--jquery-minicolors` while it should be https://www.npmjs.com/package/@claviska/jquery-minicolors

**Comment by hiqsol** [comment]
I'll take a look
