### ISSUE TITLE
bower-asset/rangy pointing to the wrong package

### ISSUE THREAD

**Issue by BreiteSeite** [hiqdev/asset-packagist#118]
## Steps to reproduce
1. visit https://asset-packagist.org/package/bower-asset/rangy

## Expected
1. Listed versions/commits are from: https://github.com/noap/rangy-1.3

## Acutal
1. Listed versions/commits are from: https://github.com/timdown/rangy

I suspect this is the issue: https://github.com/timdown/rangy/commit/822d94b957b90cf12c8cbff78ea883acdc903169

This bug totally breaks `bower-asset/bootstrap3-wysihtml5-bower` as this resolves to the wrong rangy package

```
bower-asset/bootstrap3-wysihtml5-bower v0.3.3 requires bower-asset/rangy-1.3 dev-master -> satisfiable by bower-asset/rangy-1.3[dev-master] but these conflict with your requirements or minimum-stability.
```

Also it tries to resolve to `bower-asset/rangy-1.3` which doesn't even exist: https://asset-packagist.org/package/bower-asset/rangy-1.3

**Comment by rob006** [comment]
This package is defined in this way in Bower registry: https://bower.io/search/?q=rangy

If this is incorrect, you should report it there. Asset packagist only maps bower registry to composer packages.

**Comment by BreiteSeite** [comment]
@rob006 then tell me, how would i download rangy-1.3 from asset-packagist.com, which is listed in your link.

**Comment by rob006** [comment]
It is here: https://asset-packagist.org/package/detail?fullname=bower-asset/rangy-1.3 , so you should be able to use it.

**Comment by BreiteSeite** [comment]
@rob006 no offense but did you read the description of the PR? Hover over "Get ZIP" on the page you linked and you will see it points to a totally different repository.
