### ISSUE TITLE
Ignored option asset-installer-paths in composer.json

### ISSUE THREAD

**Issue by LAV45** [hiqdev/asset-packagist#12]
All packages are installed in the directory `bower-asset` despite the settings in the composer.json
```json
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
```
https://github.com/yiisoft/yii2-app-advanced/blob/master/composer.json#L31-L36

**Comment by hiqsol** [comment]
Asset packagist  is not a plugin!
So it just can't know about settings in your `composer.json`.

What you need is a small adjustment to your application config:

```php
$config = [
        ...
        'aliases' => [
            '@bower' => '@vendor/bower-asset',
            '@npm'   => '@vendor/npm-asset',
        ],
        ...
];
```

**Comment by LAV45** [comment]
Thanks
