### ISSUE TITLE
Npm package missing

### ISSUE THREAD

**Issue by Locustv2** [hiqdev/asset-packagist#121]
I am trying to install the package: https://www.npmjs.com/package/cryptocurrency-icons

I am having the error that it could not be found, or there is some kind of typo in the name.

I tried to search the package from the page: https://asset-packagist.org/package/search?query=crypto+icon&platform=npm

But could not find it.

**Comment by hiqsol** [comment]
That's the problem of search engine used.
But direct link can always be used:

https://asset-packagist.org/package/npm-asset/cryptocurrency-icons

And now the package can be used.
