### ISSUE TITLE
Content-Length mismatch

### ISSUE THREAD

**Issue by nijilawrence** [hiqdev/asset-packagist#125]
### Please provide your `composer.json` if appropriate.

[Composer\Downloader\TransportException]                                   
  Content-Length mismatch, received 81664 bytes out of the expected 5542180

transfer closed with 5460521 bytes remaining to read:
https://asset-packagist.org/p/provider-latest/5b9d8ab2217862a4c1fa6a203ccb26bfec0436f7995790c5512d938f111efd7b.json

**Comment by hiqsol** [comment]
That was a problem with disk storage.
Please, close the issue if it is ok now.

**Comment by nijilawrence** [comment]
Thanks for getting this fixed so fast

**Comment by jcowher** [comment]
Unfortunately, I started seeing this tonight as well.

```
Downloading https://asset-packagist.org/p/provider-latest/113b5794ba27dd6964794393fee2e43aea85f1004344aea715f35fa6708ce5f1.json
Content-Length mismatch, received 130816 out of 5694137 bytes:
```

It looks like the file is being truncated after a certain point.

```
{"sha256":"058946afc6a86eb69ec17aaf4f889e2622a014f2de8d165e7db622eb4d4470ad"},"npm-asset/escape-string-regexp":{"sha256":"d3a2d573e6f75c54127335618868cf1215df4448c638636af472a0a844662f1f"},"npm-asset/unicode-length":{"sha256":"ec8f329d3f059ae52c8b734090adf88a9896a6cd98e461aa4c7ae135d938c20c"},"npm-asset/events-to-ar
```

**Comment by eelkeblok** [comment]
Same here. although the file I am seeing the problem with is 

    Downloading https://asset-packagist.org/p/provider-latest/b23437509eebb1b64069ce5f7b9afdd2325474ce59cc724a5e95f924891ce51f.json
Content-Length mismatch, received 65280 out of 5730998 bytes:

**Comment by sbt2486** [comment]
Can confirm this as well: 

![image](https://user-images.githubusercontent.com/4342278/94385961-9d2eff80-0170-11eb-957b-0d8134d6ef4b.png)

I had to temporarily remove the following from my `composer.json` in order to install any composer package again:

```
 "asset-packagist": {
            "type": "composer",
            "url": "https://asset-packagist.org"
}
```

Are you guys working on fixing this?

**Comment by hiqsol** [comment]
Yes. We're moving to other server.
Sorry for the inconveniences.
Remember, nobody pays for it :)
