### ISSUE TITLE
Content-Length mismatch

### ISSUE THREAD

**Issue by eelkeblok** [hiqdev/asset-packagist#126]
Since #125 is closed, I am reposting this as a new issue hoping that it will get more attention this way, since this is an active blocker for our development process. I hope this is OK.

**Comment by hiqsol** [comment]
This gets attention!
We're debugging it.

**Comment by amjad1233** [comment]
I am having the same issue. 
`transfer closed with 5764865 bytes remaining to read:	https://asset-packagist.org/p/provider-latest/a55259bba0c46c3ed35b9c48b8b2b0a4865578f481fcce39aad3b0fdd2a749a6.json`

**Comment by schmunk42** [comment]
Same here

```
Downloading https://asset-packagist.org/p/provider-latest/a55259bba0c46c3ed35b9c48b8b2b0a4865578f481fcce39aad3b0fdd2a749a6.json
Content-Length mismatch, received 98048 out of 5830140 bytes: (eyJwcm92aWR.....
```

```
  [Composer\Downloader\TransportException]                                   
  Content-Length mismatch, received 98048 bytes out of the expected 5830140  
```

Could you try to regenerate the json file?

**Comment by jessegrunert** [comment]
Same here, getting this error for a couple of days now!

**Comment by Krakozaber** [comment]
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)         

In RemoteFilesystem.php line 345:
                                                                             
  Content-Length mismatch, received 32512 bytes out of the expected 5830140

**Comment by hiqsol** [comment]
> Could you try to regenerate the json file?

We've run out of disk storage.
Moving to other server.

**Comment by schmunk42** [comment]
Temporary workaround in `composer.json`, installs into the same location as AP

```
    "config": {
        "fxp-asset": {
            "enabled": true,
            "installer-paths": {
                "npm-asset-library": "vendor/npm-asset",
                "bower-asset-library": "vendor/bower-asset"
            },
            "vcs-driver-options": {
                "github-no-api": true
            },
            "git-skip-update": "2 days",
            "pattern-skip-version": "(-build|-patch)",
            "optimize-with-installed-packages": false
        }
    }
```

**Comment by SilverFire** [comment]
We've moved to a new server.
Some packages might be outdated for a while, update queue is rolling
