### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by leandrogehlen** [hiqdev/asset-packagist#128]
Seems ssl certificate is expirated

![image](https://user-images.githubusercontent.com/1750751/94548353-fa858800-0226-11eb-9ed0-98434a163340.png)

**Comment by mxr576** [comment]
and now the site gives 500 server error

**Comment by hiqsol** [comment]
We're moving to other server.
Sorry for inconveniences.

**Comment by SilverFire** [comment]
We have successfully moved to a new server.
Some packages may be outdated for a while, the update queue is running
