### ISSUE TITLE
Composer 2 support for the repository

### ISSUE THREAD

**Issue by Seldaek** [hiqdev/asset-packagist#129]
Seeing issues like https://github.com/composer/composer/issues/9284 - it seems the v1 metadata approach is suboptimal for this repo, much like it was for packagist.org. That's why we did changes in Composer 2.

You can find details at https://github.com/composer/composer/blob/master/UPGRADE-2.0.md#for-composer-repository-implementors - for you especially implementing metadata-url + the new metadata format, and setting available-package-patterns to `"npm-asset/*"` would be much more efficient I think.

**Comment by Kingdutch** [comment]
I think this is a duplicate/same cause as #122 :)

**Comment by hudri** [comment]
Can you give us an update on the future of asset-packagist.org? Are there any plans to support Composer 2?

**Comment by hiqsol** [comment]
It is not the question of "support"! Composer 2 works fine with asset-packagist.org
That's the question of efficiency. At the moment we don't have any plans to dive into it. But PRs are very welcome!
