### ISSUE TITLE
[Bug] Can't fetch updates for bower-asset/elevatezoom3 and can't install it anymore in the existing project

### ISSUE THREAD

**Issue by anyt** [hiqdev/asset-packagist#131]
This package: https://asset-packagist.org/package/bower-asset/elevatezoom3 stopped working at the assets-packagist.org recently.
And now I can not use it in my composer.json as the dependency anymore.

Can you please provide a workaround or share thoughts on why it is broken?

**Comment by N3m1s** [comment]
@anyt have you managed to solve this?

**Comment by anyt** [comment]
Not really, we just switched to the fork. It looks like the author decided to delete the package.
