### ISSUE TITLE
JSONStream package confusion

### ISSUE THREAD

**Issue by artemvd** [hiqdev/asset-packagist#132]
Npm has https://www.npmjs.com/package/JSONStream and https://www.npmjs.com/package/jsonstream packages, and in search results https://asset-packagist.org/package/search?query=JSONStream&platform=bower%2Cnpm there are 2 packages, but when but they both pointing to the same url https://asset-packagist.org/package/npm-asset/jsonstream and it leads to error:

```
Problem 1
    - npm-asset/npm 4.4.1 requires npm-asset/jsonstream ~1.3.0 -> no matching package found.
```

because it tries to get the old package https://www.npmjs.com/package/jsonstream

Please help, how can the case sensitive packages names can be distinguished?

**Comment by remcoa** [comment]
Ran into the same issue yesterday and was able to fix it by adding a custom package like below.
Although this works and hopefully helps someone, I believe asset-packagist is very useful for a small set of simple npm/bower packages to add to your project, but for more complex npm packages with lots of (deep) dependencies, you'd better switch to npm itself.
I'm looking into https://packagist.org/packages/mouf/nodejs-installer right now...

```json
    "repositories": {
    	"assets": {
            "type": "composer",
            "url": "https://asset-packagist.org"
        },
        "jsonstream121": {
            "canonical": false,
            "type": "package",
            "package": {
                "name" : "npm-asset/JSONStream",
                "version": "1.2.1",
                "type": "npm-asset",
                "dist": {
                  "type": "zip",
                  "url": "https://api.github.com/repos/dominictarr/JSONStream/zipball/641402b48dbf3db5380e9bc857753c237d4ee9d9",
                  "reference": "641402b48dbf3db5380e9bc857753c237d4ee9d9"
                }
            }
        },
        "jsonstream135": {
            "canonical": false,
            "type": "package",
            "package": {
                "name" : "npm-asset/JSONStream",
                "version": "1.3.5",
                "type": "npm-asset",
                "dist": {
                  "type": "zip",
                  "url": "https://api.github.com/repos/dominictarr/JSONStream/zipball/0593d4b4e6c63c6c0e2e68463538fd83bd1eb964",
                  "reference": "0593d4b4e6c63c6c0e2e68463538fd83bd1eb964"
                },
                "source": {
                  "type": "git",
                  "url": "git://github.com/dominictarr/JSONStream.git",
                  "reference": "0593d4b4e6c63c6c0e2e68463538fd83bd1eb964"
                }
            }
        }
    }
```
