### ISSUE TITLE
HiArt Exception when search for package on website

### ISSUE THREAD

**Issue by robsch** [hiqdev/asset-packagist#135]
I searched for 'twbs-pagination' but I think it is true for all packages: Most of the time I get the HiArt exception presented. Only sometimes I see the expected matches. What is wrong here?

Seems to be the same as in #116.

Is it just a problem with the web page or is the usage of composer also concerned?

**Comment by hiqsol** [comment]
I've sent a mail to the service we use to implement search: https://libraries.io/
I've asked them to increase limit for us.
Waiting for answer.
