### ISSUE TITLE
"Package update failed"

### ISSUE THREAD

**Issue by joester89** [hiqdev/asset-packagist#139]
I am trying to install https://asset-packagist.org/package/npm-asset/qr-scanner in version 1.3.0, but compower states that the last available version is 1.2.0.

Searching it on asset-packagist.org shows that it has the latest version of 1.3.0 but when you click the link it fails fetching updates on NPM.

**Comment by Ambient-Impact** [comment]
I'm getting this with every package I've tried lately on the site. At first I thought it was that the site didn't play well with Firefox, so I checked Chrome, and the same problem shows up there too. Both browsers show a 500 error in the console for an XHR POST request to https://asset-packagist.org/package/update, so it looks like a problem with the back-end.

**Comment by GregJPreece** [comment]
Seeing the same with `fullcalendar-scheduler`. Looks like Asset Packagist has stopped synchronising for new versions with NPM.

**Comment by luked3v3l0p3r** [comment]
A similar problem appears also on "bower" packages.
