### ISSUE TITLE
Asset Packagist not resolving dependencies

### ISSUE THREAD

**Issue by alexantr** [hiqdev/asset-packagist#14]
To see the problem create test config
```json
{
    "require": {
        "bower-asset/jquery-ui": "^1.12"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}
```
And run `composer update` without installed "fxp/composer-asset-plugin".
Only jquery-ui v1.12.0.0 will be installed.

Create second config
```json
{
    "require": {
        "bower-asset/jquery-ui": "^1.12"
    }
}
```
Require "fxp/composer-asset-plugin:^1.2.0" and run `composer update`.
jquery-ui v1.12.0.1 and jquery v3.1.0 will be installed.

I tried with other bower assets and catch same bug.

Tested with composer 1.2, php 7 on windows 10 and ubuntu on windows and composer 1.2, php 5.6 on debian.

**Comment by hiqsol** [comment]
I've fixed that.
But packages info needs to be reloaded, it will take some time.

**Comment by alexantr** [comment]
:+1:
It's working now!
