### ISSUE TITLE
Wrong package version and 500 error on site

### ISSUE THREAD

**Issue by themikem** [hiqdev/asset-packagist#141]
Attempting to install npm-asset/fullcalendar results in an outdated version (5.7), whereas 5.9 is the current release.

What is odd is that 5.9.0 is reflected in first entry in the results from: https://asset-packagist.org/package/search?query=fullcalendar&platform=npm

![Screenshot 2021-10-11 103133](https://user-images.githubusercontent.com/5784219/136817190-f6c1222b-bdec-4d97-9a29-88cb84c383b7.jpg)

However, clicking on the "ready to use" button results in a 500 error when the page posts to https://asset-packagist.org/package/update and the spinning gear thus never goes away.

![Screenshot 2021-10-11 103334](https://user-images.githubusercontent.com/5784219/136817193-74c5b686-5c0c-43f7-903c-197c9b4d1b83.jpg)

Mostly, trying to install version 5.9 of this package.  Any ideas on what to do...?

Thanks!

**Comment by joester89** [comment]
Looks like it is the same as #139

**Comment by papppeter** [comment]
It looks fixed now.

![image](https://user-images.githubusercontent.com/3380880/141774030-6cbdb076-91d3-46c4-9fc4-bb8004947e18.png)
