### ISSUE TITLE
Fetch does not fetch dependencies

### ISSUE THREAD

**Issue by buzanits** [hiqdev/asset-packagist#145]
When clicking on a package on the website, the package is fetched from the sources. Good. But if the package has dependencies, they are not fetched. So installing the package fails, because the dependency packages are outdated. Fetching them manual on the website is not an apropriate workaround, because some packages have dozens of dependencies.

**Comment by SilverFire** [comment]
Hello.
Sorry for the late answer.
The dependencies are fetched asynchronously, so after adding a new package it make take some time to fetch all the package versions' dependencies.
