### ISSUE TITLE
asset-packagist.org is down again

### ISSUE THREAD

**Issue by cruno91** [hiqdev/asset-packagist#147]
### Please provide your `composer.json` if appropriate.

```
The "https://asset-packagist.org/packages.json" file could not be downloaded: failed to open stream: Operation timed out
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
```
![image](https://user-images.githubusercontent.com/1760366/172894281-05e569a3-e379-41ce-83c5-b04bd2c6d851.png)

I know the domain was renewed based on this thread: https://github.com/hiqdev/asset-packagist/issues/146#issuecomment-1106742011

I noticed this was down for us roughly 15min ago but not sure if it started earlier.

**Comment by markwooff** [comment]
Confirming it's down for our builds as well.

**Comment by minorOffense** [comment]
Yeah it's been down for about an hour. Domain is valid but the server looks to be off.

**Comment by SilverFire** [comment]
There is a problem with the server hardware, we are already working on it.
Expecting full recovery by the morning.

Sorry for the inconveniences.

**Comment by cruno91** [comment]
Thank you for the update @SilverFire

**Comment by SilverFire** [comment]
Up and running
