### ISSUE TITLE
asset-packagist.org is down again

### ISSUE THREAD

**Issue by scottatdrake** [hiqdev/asset-packagist#148]
asset-packagist.org is timing out for me. Possibly a recurrence of #147 ?

**Comment by scottatdrake** [comment]
As soon as I hit submit on this issue, it came back up. Closing!

**Comment by SilverFire** [comment]
We've added additional 500GB to the server storage and needed a system reboot.

**Comment by bim-g** [comment]
It seems that the problem, is not yet resolved

**Comment by SilverFire** [comment]
Hello. I can't see any problems now. What do you see exactly?

**Comment by bim-g** [comment]
this the error message i'm geting `curl error 28 while downloading https://asset-packagist.org/packages.json: Resolving timed out after 10000 milliseconds`

**Comment by SilverFire** [comment]
It means your PC can not resolve the hostname.

The domain is resolvable worldwide https://dnschecker.org/#A/asset-packagist.org, so you should consult with your ISP.
