### ISSUE TITLE
Queue package update requests

### ISSUE THREAD

**Issue by nkovacs** [hiqdev/asset-packagist#15]
I fetched `bower-asset/mocha` today and the website was throwing 504 errors for a few minutes while the update was happening. It's much better now that the package has already been fetched once, the update happens in about 5 seconds. The website still won't load for those 5 seconds though.

You should use a job queue and do processing in the background.

**Comment by hiqsol** [comment]
We are looking into it.

**Comment by hiqsol** [comment]
Fixed. Thank you for your notice!

Actually processing is done in the background.
Problem was with php-fpm configuration.

**Comment by nkovacs** [comment]
By background, do you mean that the ajax call happens in the background?
What I mean is that the processing happens in the web request handler, `actionUpdate`, which directly calls [`AssetPackage::update`](https://github.com/hiqdev/asset-packagist/blob/master/src/models/AssetPackage.php#L201). The problem with this is that a few people hitting `actionUpdate` can overwhelm your server.
With a job queue, you'd only queue the update in `actionUpdate` (except if an update for that package is already in the queue), and then do the update in a separate process that only reads a couple jobs from the queue at a time and processes them. That way, you'd never have more than a couple of updates running at the same time, no matter how many people click update on the website.

**Comment by hiqsol** [comment]
Good idea. We'll implement it later.

**Comment by SilverFire** [comment]
Implemented background package updating with queues.

https://asset-packagist.org/package/search?query=bower-asset%2Fmocha
