### ISSUE TITLE
Unable to search packages from the website because of HiArt Exception

### ISSUE THREAD

**Issue by HeikkiYlipaavalniemi** [hiqdev/asset-packagist#150]
The website asset-packagist.org seems to be giving an internal error when trying to search for packages.

Example: https://asset-packagist.org/package/search?query=test&platform=bower%2Cnpm

**Comment by SilverFire** [comment]
Hi, thanks for a report.

https://libraries.io/ API now requires API_KEY, otherwise, we hit a rate limit too early.
We'll update integration to use an API key soon.

**Comment by SilverFire** [comment]
Done: https://github.com/hiqdev/yii2-hiart-librariesio/commit/34e1bf964f47e67442888d4f17b4251811600031

Now search works as expected
