### ISSUE TITLE
Bower package updates are shown fetched but in reality not

### ISSUE THREAD

**Issue by kaszarobert** [hiqdev/asset-packagist#156]
- Search for papaparse (https://asset-packagist.org/package/search?query=papaparse+&platform=bower%2Cnpm) 
- According to the search result page, the latest is `Latest Release: 5.4.1 at Mar 23, 2023, 12:48:23 PM (3 months ago)`
- Open its page (https://asset-packagist.org/package/bower-asset/papaparse) and there's no 5.4.1, the latest is still an older: 5.3.2, therefore you cannot download it.

I did not experience this with npm-asset versions, only with bower.

**Comment by SilverFire** [comment]
Hello!

I don't see this package on Bower anymore: https://bower.io/search/?q=papaparse, and the search on Bower website does not work at all.

It seems that Bower support is discontinued and you should switch to NPM

**Comment by kaszarobert** [comment]
I'm also getting "Sorry, there was an error while fetching repositories." but for every package. Plus looking at bower repo last release Jan 19, 2021, last commit Mar 14, 2022. Then it seems it is time for Drupal modules to move away from bower-asset dependencies completely. Thanks for the quick response!
