### ISSUE TITLE
Possible to add version number of package in folder name

### ISSUE THREAD

**Issue by chross** [hiqdev/asset-packagist#158]
Is it possible to add multiple packages with trailing version number, like in composer, for when I need two different versions of the same asset at once? I did not find this option in the oomphinc/composer-installers-extender plugin. Should I pose this question there?

**Comment by SilverFire** [comment]
Hi!
Could you show an example how you install multiple versions of the same Composer package?

**Comment by chross** [comment]
Sorry, my bad, I couldn't. Please disregard this comment, I got something mixed up in my folder structure.
Still, I wish I could install multiple versions for npm-assets.

**Comment by SilverFire** [comment]
The only idea I have is to create multiple dirs with different `composer.json` files and have a separate `vendor/` dir in each
