### ISSUE TITLE
http error 500 fetching npm package

### ISSUE THREAD

**Issue by surikat** [hiqdev/asset-packagist#16]
Hello,
on fetching npm-asset/color-name (on https://asset-packagist.org/), and with some others npm librairies I get an http error 500 on the xhr request https://asset-packagist.org/site/update

here is the returned error:

Exception 'RuntimeException' with message 'Failed to execute git clone --mirror 'git+ssh://git@github.com/harthur/color-string.git' '/var/www/.composer/cache/vcs/git-ssh---git-github.com-harthur-color-string.git/'

Cloning into bare repository '/var/www/.composer/cache/vcs/git-ssh---git-github.com-harthur-color-string.git'...
Could not create directory '/var/www/.ssh'.
Host key verification failed.
fatal: Could not read from remote repository.

**Comment by surikat** [comment]
Thank to you.
You're welcome.

**Comment by surikat** [comment]
Sorry, It seem to work with some libs but with npm-asset/chartjs-color-string or npm-asset/nodeunit the problem persist

**Comment by hiqsol** [comment]
Please, try now again.

**Comment by surikat** [comment]
Nickel, thanks

**Comment by surikat** [comment]
Sorry again, the problem reappears with npm-asset/babel-generator

**Comment by surikat** [comment]
Oups my bad, it's just a not found error
