### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by EvilKarter** [hiqdev/asset-packagist#162]
Hi, 
when I go to https://asset-packagist.org/package/npm-asset/lighthouse, the first thing I see is the list of available packages. 
Then I see the gear wheel that something is loaded again. However, the AJAX request dies with a 500 status code.

Request URL: https://asset-packagist.org/package/update
Request Method: POST
Status Code: 500 Internal Server Error

When I search for "ligthouse" on the home page, I see the latest release is version 11.2:
![image](https://github.com/hiqdev/asset-packagist/assets/3779278/13dafe53-bbf0-4e47-8532-9b00384b5797)
This version also matches the repository of the project: https://github.com/GoogleChrome/lighthouse/tree/v11.2.0

If the package is installed via cmd:
`composer require npm-asset/lighthouse`
in the composer.json wil be added
`"npm-asset/lighthouse": "^1.0",`

If I add the line manually
`"npm-asset/lighthouse": "^11.2",`
and run `composer update` I get the following error:

 Root composer.json requires npm-asset/lighthouse ^11.2, found npm-asset/lighthouse[dev-win-quibble-fix-tests-w-mocks-file, ..., dev-patch-package-pptr, 0.0.1, 0.0.2, v0.1.1, 1.0.0, ..., 1.6.5, 2.0.0-alpha.2, ..., 2.9.4, 3.
0.0-alpha1, ..., 3.2.1, 4.0.0-alpha.0, ..., 4.x-dev, 5.0.0, ..., 5.6.0, 6.0.0-beta.0, ..., 6.5.0, 7.0.0-dev, ..., 7.5.0, 8.0.0-dev, ..., 8.6.0, 9.0.0-dev, ..., 9.6.8, 10.0.0-dev, ..., 10.0.2, 100.x-dev, 600.x-dev] but it does not match the constraint.

**Comment by SilverFire** [comment]
Hi. Thanks for the report!
We've hit a memory limit, trying to resolve dependencies.
Increased from 128mb to 256mb
