### ISSUE TITLE
Bower-Asset Jquery - missing latest version since today

### ISSUE THREAD

**Issue by ItsReddi** [hiqdev/asset-packagist#167]
Hi,
https://asset-packagist.org/package/bower-asset/jquery
![grafik](https://github.com/user-attachments/assets/4c1a6f1a-e02e-42a3-9253-5e4eb8397c45)

Is missing at least the 3.7.1 version since today.

**Comment by rob006** [comment]
I can confirm this issue, I often see this bug where latest versions are missing. It looks like package is synced from 2 sources and one of them is incomplete. Usually using "Fetch updates from Bower" button helps, but after some time problem returns.

Also, some packages constantly switches `source.url` in this way (back and forth) - it could have similar cause:

![a197937e](https://github.com/user-attachments/assets/3f4e2598-2c44-4eef-b0ae-13ca2478a1a7)

**Comment by ItsReddi** [comment]
Yes, correct **at the moment**. But its random, sometimes it is available, sometimes not.
see, https://github.com/yiisoft/yii2/issues/20067
It is not only jquery.

**Comment by rob006** [comment]
@SilverFire it is gone again

![a12b7d4c](https://github.com/user-attachments/assets/a3b82f4e-c743-4dcf-9b54-189149634993)

**Comment by sonnykt** [comment]
Confirming it's gone again:
```
  Problem 1
    - Root composer.json requires bower-asset/jquery == 3.7.1.0 (exact version match), found bower-asset/jquery[dev-main, 1.0-alpha1, ..., 1.12.4, 2.0.0-beta1, ..., 2.2.4, 3.0.0-alpha1, ..., 3.6.4] but these do not match your constraint and are therefore not installable. Make sure you either fix the constraint or avoid updating this package to keep the one present in the lock file (bower-asset/jquery[3.7.1])
    - ```
