### ISSUE TITLE
file_put_contents permission denied

### ISSUE THREAD

**Issue by surikat** [hiqdev/asset-packagist#17]
with the package npm-asset/tap, I get:

PHP Warning 'yii\base\ErrorException' with message 'file_put_contents(/home/sol/prj/hiqdev/asset-packagist.org/web/p/npm-asset/tap/b0f37226924cdc1de25c67330f5327122767cf0d514239e309df5449e34ec09d.json): failed to open stream: Permission denied' 

in /home/sol/prj/hiqdev/asset-packagist.org/vendor/hiqdev/asset-packagist/src/components/Storage.php:83

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'file_put_conten...', '/home/sol/prj/h...', 83, Array)
#1 /home/sol/prj/hiqdev/asset-packagist.org/vendor/hiqdev/asset-packagist/src/components/Storage.php(83): file_put_contents('/home/sol/prj/h...', '{"packages":{"n...')
#2 /home/sol/prj/hiqdev/asset-packagist.org/vendor/hiqdev/asset-packagist/src/models/AssetPackage.php(205): hiqdev\assetpackagist\components\Storage->writePackage(Object(hiqdev\assetpackagist\models\AssetPackage))
#3 /home/sol/prj/hiqdev/asset-packagist.org/vendor/hiqdev/asset-packagist/src/controllers/SiteController.php(85): hiqdev\assetpackagist\models\AssetPackage->update()
#4 [internal function]: hiqdev\assetpackagist\controllers\SiteController->actionUpdate()
#5 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#6 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#7 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('update', Array)
#8 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('site/update', Array)
#9 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#10 /home/sol/prj/hiqdev/asset-packagist.org/web/index.php(8): yii\base\Application->run()
#11 {main}

**Comment by hiqsol** [comment]
Fixed permissions.
Thank you for the notice.

**Comment by surikat** [comment]
Thanks
