### ISSUE TITLE
not found error with npm existing package

### ISSUE THREAD

**Issue by surikat** [hiqdev/asset-packagist#18]
with npm-asset/babel-generator I get e not found error,
but the library actually exists in npm

Exception 'RuntimeException' with message 'Failed to execute git clone --mirror 'https://**_:**_@github.com/babel/babel/tree/master/packages/babel-generator.git' '/var/www/.composer/cache/vcs/git-github.com-babel-babel-tree-master-packages-babel-generator.git/'

Cloning into bare repository '/var/www/.composer/cache/vcs/git-github.com-babel-babel-tree-master-packages-babel-generator.git'...
fatal: repository 'https://**_:**_@github.com/babel/babel/tree/master/packages/babel-generator.git/' not found
' 

in /home/sol/prj/hiqdev/asset-packagist.org/vendor/composer/composer/src/Composer/Util/Git.php:272

Stack trace:
#0 /home/sol/prj/hiqdev/asset-packagist.org/vendor/composer/composer/src/Composer/Util/Git.php(195): Composer\Util\Git->throwException('Failed to execu...', 'git@github.com:...')
#1 /home/sol/prj/hiqdev/asset-packagist.org/vendor/composer/composer/src/Composer/Repository/Vcs/GitDriver.php(81): Composer\Util\Git->runCommand(Object(Closure), 'git@github.com:...', NULL, true)
#2 /home/sol/prj/hiqdev/asset-packagist.org/vendor/fxp/composer-asset-plugin/Repository/Vcs/GitHubDriver.php(149): Composer\Repository\Vcs\GitDriver->initialize()
#3 /home/sol/prj/hiqdev/asset-packagist.org/vendor/composer/composer/src/Composer/Repository/Vcs/GitHubDriver.php(433): Fxp\Composer\AssetPlugin\Repository\Vcs\GitHubDriver->setupGitDriver('git@github.com:...')
#4 /home/sol/prj/hiqdev/asset-packagist.org/vendor/composer/composer/src/Composer/Repository/Vcs/GitHubDriver.php(312): Composer\Repository\Vcs\GitHubDriver->attemptCloneFallback()
#5 /home/sol/prj/hiqdev/asset-packagist.org/vendor/fxp/composer-asset-plugin/Repository/Vcs/AbstractGitHubDriver.php(62): Composer\Repository\Vcs\GitHubDriver->getContents('https://api.git...', true)
#6 /home/sol/prj/hiqdev/asset-packagist.org/vendor/composer/composer/src/Composer/Repository/Vcs/GitHubDriver.php(405): Fxp\Composer\AssetPlugin\Repository\Vcs\AbstractGitHubDriver->getContents('https://api.git...', true)
#7 /home/sol/prj/hiqdev/asset-packagist.org/vendor/composer/composer/src/Composer/Repository/Vcs/GitHubDriver.php(64): Composer\Repository\Vcs\GitHubDriver->fetchRootIdentifier()
#8 /home/sol/prj/hiqdev/asset-packagist.org/vendor/composer/composer/src/Composer/Repository/VcsRepository.php(91): Composer\Repository\Vcs\GitHubDriver->initialize()
#9 /home/sol/prj/hiqdev/asset-packagist.org/vendor/fxp/composer-asset-plugin/Repository/AbstractAssetVcsRepository.php(121): Composer\Repository\VcsRepository->getDriver()
#10 /home/sol/prj/hiqdev/asset-packagist.org/vendor/fxp/composer-asset-plugin/Repository/AssetVcsRepository.php(39): Fxp\Composer\AssetPlugin\Repository\AbstractAssetVcsRepository->initDriver()
#11 /home/sol/prj/hiqdev/asset-packagist.org/vendor/composer/composer/src/Composer/Repository/ArrayRepository.php(181): Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->initialize()
#12 /home/sol/prj/hiqdev/asset-packagist.org/vendor/hiqdev/asset-packagist/src/models/AssetPackage.php(215): Composer\Repository\ArrayRepository->getPackages()
#13 /home/sol/prj/hiqdev/asset-packagist.org/vendor/hiqdev/asset-packagist/src/models/AssetPackage.php(204): hiqdev\assetpackagist\models\AssetPackage->prepareReleases(Object(Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository))
#14 /home/sol/prj/hiqdev/asset-packagist.org/vendor/hiqdev/asset-packagist/src/controllers/SiteController.php(85): hiqdev\assetpackagist\models\AssetPackage->update()
#15 [internal function]: hiqdev\assetpackagist\controllers\SiteController->actionUpdate()
#16 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#17 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#18 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('update', Array)
#19 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('site/update', Array)
#20 /home/sol/prj/hiqdev/asset-packagist.org/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#21 /home/sol/prj/hiqdev/asset-packagist.org/web/index.php(8): yii\base\Application->run()
#22 {main}

**Comment by hiqsol** [comment]
This one is harder.
I'm looking into it.

**Comment by SilverFire** [comment]
Sorry for a long reply.

Currently package is available [on asset-packagist.org](https://asset-packagist.org/package/search?query=npm-asset%2Fbabel-generator) and installable in composer:

```json
{
    "require": {
        "npm-asset/babel-generator": "*"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org/"
        }
    ]
}
```

```bash
Loading composer repositories with package information
Updating dependencies (including require-dev)

Package operations: 16 installs, 0 updates, 0 removals
  - Installing npm-asset/trim-right (1.0.1.0): Downloading (100%)         
  - Installing npm-asset/source-map (0.5.6.0): Downloading (100%)         
  - Installing npm-asset/lodash (4.17.4.0-patch1): Downloading (100%)         
  - Installing npm-asset/jsesc (1.3.0.0): Downloading (100%)         
  - Installing npm-asset/number-is-nan (1.0.1.0): Downloading (100%)         
  - Installing npm-asset/is-finite (1.0.2.0): Downloading (100%)         
  - Installing npm-asset/repeating (2.0.1.0): Downloading (100%)         
  - Installing npm-asset/detect-indent (4.0.0.0): Downloading (100%)         
  - Installing npm-asset/to-fast-properties (1.0.2.0): Downloading (100%)         
  - Installing npm-asset/esutils (2.0.2.0): Downloading (100%)         
  - Installing npm-asset/regenerator-runtime (0.10.4.0): Downloading (100%)         
  - Installing npm-asset/core-js (2.4.1.0): Downloading (100%)         
  - Installing npm-asset/babel-runtime (6.23.0.0): Downloading (100%)         
  - Installing npm-asset/babel-types (6.24.1.0): Downloading (100%)         
  - Installing npm-asset/babel-messages (6.23.0.0): Downloading (100%)         
  - Installing npm-asset/babel-generator (6.24.1.0): Downloading (100%)         
Writing lock file
Generating autoload files
```

**Comment by surikat** [comment]
Great, thank's :-)
