### ISSUE TITLE
Write installed assets to different folder

### ISSUE THREAD

**Issue by holtkamp** [hiqdev/asset-packagist#2]
Currently all assets are installed in the ```vendor``` dir, which is logical. 
However, this folder is 'outside' the ```public``` folder that our web server serves to the web:

```
projectDir/vendor/bower-asset/bootstrap //currently
projectDir/public/vendor/bower-assets/bootstrap //preferred
```

Would this be possible or should this be done 'manually' using a postInstall script?

**UPDATE**
I had a look at https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md, but that does not allow arbitrary paths, since it might overwrite users folders.

Luckily this extension https://github.com/oomphinc/composer-installers-extender does support it like this:

```json
  "repositories": [
      {
          "type": "composer",
          "url": "https://asset-packagist.org"
      }
  ],
  "require": {
      "oomphinc/composer-installers-extender": "*",
      "bower-asset/bootstrap": "^3.3",
      "npm-asset/jquery": "^2.2"
  },
  "extra": {
     "installer-types": ["library"],
     "installer-paths": {
       "public/assets/{$name}/": ["type:library"]
     }
   }
```

**Comment by holtkamp** [comment]
Maybe this can be included in the documentation? Closing issue

**Comment by hiqsol** [comment]
The main point is that asset-packagist.org is just a repository. It is NOT a plugin.
So it can't affect where packages are installed.

I just found that same solution as you :)

**Comment by hiqsol** [comment]
Updated [documentation](https://asset-packagist.org/site/about).
