### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by githubjeka** [hiqdev/asset-packagist#28]
![image](https://cloud.githubusercontent.com/assets/874234/23507792/b54d0308-ff5f-11e6-8095-bdf6aaeaf499.png)

I was waiting and came to here

P.S. A typo by named

**Comment by rodrigoaguilera** [comment]
I was searching for jquery.easing
https://asset-packagist.org/site/search?query=jquery.easing

But the search removes the dots from the package name

**Comment by SilverFire** [comment]
Roger that, will check this problem

**Comment by rodrigoaguilera** [comment]
Wow, thank you. Is there a way to support this project financially?

**Comment by SilverFire** [comment]
Fixed both. Will manage to release soon

**Comment by SilverFire** [comment]
@rodrigoaguilera thank you for your initiative to support asset-packagist.
We haven't thought about any donation campaign, so we don't have any legal way to get money from you right now.
