### ISSUE TITLE
Composer search doesn't work

### ISSUE THREAD

**Issue by padlyuck** [hiqdev/asset-packagist#3]
In case when asset-packagist.org added as repository to [~/.composer/config.json](https://getcomposer.org/doc/03-cli.md#composer-home-config-json) search commands doesn't work
```bash
$ composer require
Search for a package: yiisoft
  [Composer\Downloader\TransportException]                                                                       
  The "https://asset-packagist.org/search.json?q=yiisoft" file could not be downloaded (HTTP/1.1 404 Not Found)
 ```

**Comment by padlyuck** [comment]
I checked by adding the repository directly to a file - get the same result.

**Comment by hiqsol** [comment]
Ok, I'll fix it.
But asset-packagist is not supposed to be put to global composer.
You should put it to composer.json of the project.

**Comment by hiqsol** [comment]
Works fine now :)

**Comment by padlyuck** [comment]
Thanks!
