### ISSUE TITLE
Int.js release 1.2.6 not exists

### ISSUE THREAD

**Issue by edgardmessias** [hiqdev/asset-packagist#33]
`npm-asset/intl` and `bower-asset/intl` show release 1.2.6, but not exists.

GitHub: https://github.com/andyearnshaw/Intl.js/releases
NPM: http://registry.npmjs.org/intl
Bower: `bower info intl`

**Comment by SilverFire** [comment]
fxp/composer-asset-plugin provides this information, so could you open this issue in https://github.com/fxpio/composer-asset-plugin?

**Comment by edgardmessias** [comment]
Composer: `"minimum-stability": "stable",`

With `fxpio/composer-asset-plugin` install 1.2.5
With `asset-packagist` install 1.2.6

**Comment by edgardmessias** [comment]
The bower-asset/Leaflet.extra-markers same problem double release 1.0.6.

The problem is: if package contains version in bower.json, two packages are generated, one for dev-master, and another for version in bower.json.

She the Commit SHA.

**Comment by edgardmessias** [comment]
I solved the problem, I'm creating a pull request.
