### ISSUE TITLE
asset-packagist service seem to be down

### ISSUE THREAD

**Issue by surikat** [hiqdev/asset-packagist#4]
Hello,
first I want to thanks you for this great tool !

the packages.json is empty
https://asset-packagist.org/packages.json:
{"providers-url":"/p/%package%/%hash%.json","provider-includes":{"p/provider-latest/%hash%.json":{"sha256":"c8e2fb08bb22a987ed31aea7cf391b3801a7b52b19dbd397fc38f9aee2593044"}}}

**Comment by hiqsol** [comment]
I don't see any problems.

`packages.json` is just as it should be :)
It doesn't contain packages list.

List of packages is here https://asset-packagist.org/p/provider-latest/c8e2fb08bb22a987ed31aea7cf391b3801a7b52b19dbd397fc38f9aee2593044.json

**Comment by surikat** [comment]
Ok, well, I understand, I thought that if my packages didn't load it was because there were an error and I saw the request of composer to that file, but now I see that you don't handle all libraries of the bower registry. Sorry, my bad :)
