### ISSUE TITLE
Install an asset to a custom path

### ISSUE THREAD

**Issue by rodrigoaguilera** [hiqdev/asset-packagist#51]
I had a workflow working to install assets on custom paths but I can't make it work anymore and assets go to vendor/ always.

Here is my composer.json
```json
{
    "name": "oomphinc/composer-test",
    "repositories": [
	{
		"type": "composer",
		"url": "https://asset-packagist.org"
	}
    ],
    "require": {
        "oomphinc/composer-installers-extender": "1.1.2",
        "psr/log": "1.0.2",
        "bower-asset/bootstrap-sass": "3.3.7"
    },
    "extra": {
        "installer-types" : [ "library" ],
        "installer-paths": {
            "otherpath": ["bower-asset/bootstrap-sass"],
            "thispath": ["psr/log"],
            "morepaths": ["type:bower-asset"]
               
        }
    }
} 
```
The bootstrap-sass always end up in vendor but the psr/log gets installed in a custom path
I also reported it here
https://github.com/oomphinc/composer-installers-extender/issues/6

Have the feeling is because now this repo sets a "type" without a require for composer/installers

https://packagist.org/packages/composer/installers
Here is explained that both things are needed for the custom path to work.

**Comment by hiqsol** [comment]
You missed to specify `bower-asset` among `installer-types`:

```json
    "extra": {
        "installer-types" : [ "library", "bower-asset"],
```
in my case it was just enough and everything looks as expected after `composer update`

2. But there's still not fixed problem with composer installer plugins.
For composer/installers or composer-installers-extender to work properly it needs to be processed/installed by composer BEFORE those packages you want to be installed in a specific way.
But composer has no way to ensure an order of package installation. And this is the deliberate decision of composer creators. 
In my case installation order was:

```
Package operations: 5 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.3.0): Loading from cache
  - Installing oomphinc/composer-installers-extender (v1.1.2): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing bower-asset/jquery (3.2.1): Loading from cache
  - Installing bower-asset/bootstrap-sass (v3.3.7): Loading from cache
```

And composer-installers-extender got installed before assets and everything went as expected.
But sometimes it is necessary to run `composer install` twice...
See https://github.com/oomphinc/composer-installers-extender/issues/6

**Comment by rodrigoaguilera** [comment]
Thank you so much!

I thought  "installer-types" was just "default for packages with no type" but I get it better.

I am aware of the other problem. I opened the issue because this time that was not the case.
