### ISSUE TITLE
Unable to install scoped packages

### ISSUE THREAD

**Issue by EvgenyOrekhov** [hiqdev/asset-packagist#54]
```sh
composer require npm-asset/@twinscom/uploader-client
```

fails with the following message:

```txt
[InvalidArgumentException]                                                                                                                 
  Could not find package npm-asset/@twinscom/uploader-client at any version for your minimum-stability (stable). Check the package spelling  
   or your minimum-stability
```

The package version is `1.0.0` and the package's repository has tag `v1.0.0`.

My `composer.json`:

```json
{
    "name": "my-app",
    "description": "My app",
    "type": "project",
    "minimum-stability": "stable",

    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ],

    "require": {
        "php": ">=7.1.0"
    }
}
```

**Update**
The package's page on npmjs.com: <https://www.npmjs.com/package/@twinscom/uploader-client>

**Comment by hiqsol** [comment]
Need to learn more about scoped packages...

**Comment by hiqsol** [comment]
I've fixed the problem on dev. Will be released soon (hope tomorrow).
You will need to use package name in composer-compatible form:
`npm-asset/twinscom--uploader-client`

**Comment by hiqsol** [comment]
`npm-asset/twinscom--uploader-client` works now.

To add other scoped packages use full package name in search.
E.g. `npm-asset/twinscom--uploader-client`
