### ISSUE TITLE
Use a fork of bower asset

### ISSUE THREAD

**Issue by CyanoFresh** [hiqdev/asset-packagist#55]
### Please provide your `composer.json` if appropriate.
Hello. How I can require my own fork with this tool? In composer-asset-plugin I could specify 
```json
"asset-repositories": [
      {
        "type": "bower-github",
        "url": "https://github.com/CyanoFresh/intro.js",
        "name": "bower-asset/intro.js"
      }
    ]
```
and it was downloading my fork

**Comment by hiqsol** [comment]
Is it going to be permanent fork?
Why not create real packagist package for it?

**Comment by CyanoFresh** [comment]
Till author apply my pull request. Maybe author will not accept it. Composer and asset had this functionality

**Comment by cebe** [comment]
doesn't this work? https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

**Comment by hiqsol** [comment]
Yes, it is only necessary to add `composer.json` into the fork.
