### ISSUE TITLE
Package update failed: bower-asset/eve

### ISSUE THREAD

**Issue by mazurva** [hiqdev/asset-packagist#58]
Package update failed: bower-asset/eve

[Composer\Repository\InvalidRepositoryException]                                                                                       
  No valid bower.json was found in any branch or tag of https://github.com/DmitryBaranovskiy/eve.git, could not load a package from it.

**Comment by hiqsol** [comment]
There is no https://github.com/DmitryBaranovskiy/eve.git repository anymore.
So this bower package is not functional anymore.

See NPM `eve` package https://asset-packagist.org/package/search?query=npm-asset%2Feve
I hope it is the same package. It is developped by Dmitry Baranovskiy too.
