### ISSUE TITLE
bootstrap-vue Package update failed

### ISSUE THREAD

**Issue by indicalabs** [hiqdev/asset-packagist#59]
### Please provide your `composer.json` if appropriate.

The "bootstrap-vue" package available on npm but 
> 
> Package update failed
> Could you ensure this package exists on npmjs.com?
> Think asset-packagist is guilty? Report on GitHub

**Comment by SilverFire** [comment]
Cross-linking to https://github.com/fxpio/composer-asset-plugin/issues/303

**Comment by hiqsol** [comment]
It is fixed some time ago.
