### ISSUE TITLE
What version of packages used on asset-packagist.org ?

### ISSUE THREAD

**Issue by anyt** [hiqdev/asset-packagist#60]
I installed locally from master and also tried hiqsite branch and 0.1.0 tag, but I didn't get same website as on the asset-packagist.org.

Searchbox looks different, I have extra select with Bower and Npm options and also I don't have fancy gear when ajax requests sent, search results looks different too. 

What should I use to install same version as used on asset-packagist.org?

**Comment by hiqsol** [comment]
Actually, we have a bit outdated version on asset-packagist.org site.

master is fresher and indeed has improved search with options.
It will be released soon.
So you should not strive to get 'same version as on asset-packagist.org'
Your installation should look like this: http://new.asset-packagist.org/

Did you follow instructions from here?
https://github.com/hiqdev/asset-packagist.dev

**Comment by anyt** [comment]
it looks like http://new.asset-packagist.org/
Thank you for explaining.

**Comment by hiqsol** [comment]
I've found a bug with `fancy gear` not showing up.
Fix will be available soon.
And I'll try install the whole project from very beginning to check if everything is still ok cause many of used packages are quickly evolving.

**Comment by hiqsol** [comment]
I've pushed the fix. And reinstalled new.asset-packagist.org
Everything looks fine now.
