### ISSUE TITLE
bower-asset/jquery.floatThead no version fetched

### ISSUE THREAD

**Issue by cruzcraul** [hiqdev/asset-packagist#62]
Hi,

I'm interesting in https://asset-packagist.org/package/detail?fullname=bower-asset/jquery.floatThead but no versions fetched.

is a bug?

Thanks :)
![jquery floatthead](https://user-images.githubusercontent.com/9257605/28983277-a99306d2-791e-11e7-9430-dee2d5c289f7.png)

**Comment by hiqsol** [comment]
This is still this case sensitivity problem: https://github.com/hiqdev/asset-packagist/issues/26

Unfortunately there is no solution yet.

**Comment by SilverFire** [comment]
Closing as a duplicate
