### ISSUE TITLE
"ignore" section in bower.json is ignored

### ISSUE THREAD

**Issue by alexantr** [hiqdev/asset-packagist#63]
Files from bower's "ignore" section are not ignoring.

For example Bootstrap 3 bower.json has:
```json
{

  "ignore": [
    "/.*",
    "_config.yml",
    "CNAME",
    "composer.json",
    "CONTRIBUTING.md",
    "docs",
    "js/tests",
    "test-infra"
  ],

}
```

After `composer install` (or `composer update`) we have files in "vendor/bower-asset/bootstrap":

with `fxp/composer-asset-plugin`:
```
dist/
fonts/
grunt/
js/
less/
nuget/
Gemfile
LICENSE
Gruntfile.js
package.js
bower.json
package.json
Gemfile.lock
CHANGELOG.md
ISSUE_TEMPLATE.md
README.md
```
Folder size 2.17 MiB

with `asset-packagist`:
```
dist/
docs/
fonts/
grunt/
js/
less/
nuget/
.editorconfig
.gitattributes
.gitignore
CNAME
Gemfile
LICENSE
Gruntfile.js
package.js
bower.json
composer.json
package.json
Gemfile.lock
CHANGELOG.md
CONTRIBUTING.md
ISSUE_TEMPLATE.md
README.md
.hound.yml
.travis.yml
_config.yml
```
Folder size 11.05 MiB

As result my folder `bower-asset` with all packages has 40.22 MiB instead 10.86 MiB.

**Comment by hiqsol** [comment]
Does composer has this or similar function?

**Comment by alexantr** [comment]
composer uses .gitattributes from repo.
bower uses "ignore" from bower.json.

When installing package with `bower install bootstrap` files from "ignore" will be not downloaded.

**Comment by edgardmessias** [comment]
I can see two solutions:
* Plugin for composer to remove files after install
* Create the packages on the server already without the files

The `fxp/composer-asset-plugin` plugin removes the files after installing

See https://github.com/fxpio/composer-asset-plugin/blob/61786a1e04d26d26701bc682c543b815be2a3cfa/Installer/AssetInstaller.php#L104-L118

**Comment by alexantr** [comment]
> Create the packages on the server already without the files
This variant would be very nice!
