### ISSUE TITLE
No versions for objectFitPolyfill

### ISSUE THREAD

**Issue by Berdir** [hiqdev/asset-packagist#65]
https://asset-packagist.org/package/search?query=objectFitPolyfill&platform=bower%2Cnpm

The overview shows v2.0.5 for both bower and npm asset. But https://asset-packagist.org/package/bower-asset/objectFitPolyfill is empty. 

I tried a cache refresh but didn't help.

Maybe related to the uppercase/lowercase problems?

**Comment by hiqsol** [comment]
Yes, this is case sensitivity problem.
See https://github.com/hiqdev/asset-packagist/issues/26
Solution is under discussion now.
