### ISSUE TITLE
Documentation on switching from fxp/composer-asset-plugin

### ISSUE THREAD

**Issue by francislavoie** [hiqdev/asset-packagist#66]
I already have a ton of stuff installed with `fxp/composer-asset-plugin`. I added the `"repositories"` section to my composer.json, but running `composer update` still tries to use the github API. Is there a way to transition nicely, i.e. make it use the same installed versions as the base without needing to re-install everything for it to use `asset-packagist` from the start?

**Comment by SilverFire** [comment]
Try to uninstall `fxp/composer-asset-plugin`, remove `composer.lock` in your project, clear caches using `composer clear-cache` and then run `composer update`

**Comment by francislavoie** [comment]
That seemed to work. Shouldn't that be documented somewhere? Thanks!

**Comment by hiqsol** [comment]
https://asset-packagist.org/site/about
