### ISSUE TITLE
NPM version conflicts & SASS import scoped package problem

### ISSUE THREAD

**Issue by phuczeero** [hiqdev/asset-packagist#71]
1/ Using **fxp/composer-asset-plugin**, i can [Solve the conflicts of asset dependencies](https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/index.md#solve-the-conflicts-of-asset-dependencies), does this repository support it?

2/ When i [install individual components package](https://github.com/material-components/material-components-web#installing-individual-components) and use scss file, it throw an error
`Error: File to import not found or unreadable: @material/button/mdc-button.`

All scoped components were installed in vendor named material--\<package\>, not @material/\<package\>

My **composer.json**
```
"require": {
    "php": ">=5.4.0",
    "yiisoft/yii2": "~2.0.6",
    "npm-asset/material-components-web": "~0.21.1"
}
```

**Comment by hiqsol** [comment]
1. No, I'm afraid it's impossible to force resolutions without fxp plugin. I don't know if composer supports such function.
2. Composer doesn't support `@` and `/` symbols in package names so fxp plugin (and asset-packagist) does such conversion: `@scope/package` -> `scope--package`.
