### ISSUE TITLE
asset-packagist conflicts with fxpio/composer-asset-plugin

### ISSUE THREAD

**Issue by schmunk42** [hiqdev/asset-packagist#72]
My composer plugins:

```
> composer global show
Changed current directory to /Users/tobias/.composer
fxp/composer-asset-plugin v1.4.1 NPM/Bower Dependency Manager for Composer
```

Problematic `composer.json`

```
{
    "require": {
        "dmstr/yii2-adminlte-asset": ">=2.0"
    },
    "repositories": [
      {
        "type": "composer",
        "url": "https://asset-packagist.org"
      }
    ]
}
```

Running

    composer update -vvv

fails.

Running

    composer update -vvv --no-plugins

works.

What also works is this:

```
{
    "require": {
        "dmstr/yii2-adminlte-asset": ">=2.0"
    }
}
```

The error

```
Adding VCS repository bower-asset/eve
Executing command (CWD): git clone --mirror 'https://github.com/DmitryBaranovskiy/eve.git' '/Users/tobias/.composer/cache/vcs/https---github.com-DmitryBaranovskiy-eve.git/'
Executing command (CWD): git clone --mirror 'git@github.com:DmitryBaranovskiy/eve.git' '/Users/tobias/.composer/cache/vcs/https---github.com-DmitryBaranovskiy-eve.git/'
Executing command (CWD): git --version

                                                                                                                                         
  [Composer\Repository\InvalidRepositoryException]                                                                                       
  No valid bower.json was found in any branch or tag of https://github.com/DmitryBaranovskiy/eve.git, could not load a package from it.                          
```

---

In version `2.0` of my package I had included [`bower-asset/admin-lte`](https://github.com/dmstr/yii2-adminlte-asset/blob/9f3c5b8b771bac729f5c88a375ad5a0fab84f30c/composer.json#L21) this was moved to a composer package from `2.1` on.

I can't really say why this is happening, but it's a strange edge case, when having ap and c-a-p running together.

See also 
- https://github.com/dmstr/yii2-adminlte-asset/issues/133#issuecomment-337179853
- https://github.com/dmstr/yii2-adminlte-asset/issues?q=is%3Aissue+eve+is%3Aclosed

CC: @francoispluchino @samdark @cebe

**Comment by hiqsol** [comment]
Do you receive this error without asset-packagist?

**Comment by cebe** [comment]
> In version 2.0 of my package I had included bower-asset/admin-lte this was moved to a composer package from 2.1 on.

but the composer package name is not `bower-asset/admin-lte` is it? it should not matter if it has a different name.

> when having ap and c-a-p running together.

its not a good idea to do that...

**Comment by schmunk42** [comment]
> Do you receive this error without asset-packagist?

No, it's the second example without `repositories`. I only get the error, when using both.

> its not a good idea to do that...

Yeah, might be, but the fact is that many people have a global installation of the plugin and you'd have to disable it manually or in `composer.json` in order to actually use asset-packagist. Normally the plugin takes precedence.

**Comment by schmunk42** [comment]
@hiqsol You might have a look at the current `json` output of `bower-asset/admin-lte` from asset-packagist. And compare this with the output generated *now* by the asset plugin.

It's just an idea, but maybe this is related to some redirect which is resolved when using the plugin, but not when using static json files.

Related stuff from the web:
- https://github.com/DmitryBaranovskiy/raphael/issues/993
- http://www.yiiframework.com/forum/index.php/topic/75524-invalidrepositoryexception-githubcomdmitrybaranovskiyevegit/
- http://yiiframework.ru/forum/viewtopic.php?t=44976
- https://github.com/mdmsoft/yii2-admin/issues/353

**Comment by and800** [comment]
@schmunk42 it seems that if you want to use asset-packagist, you may simply disable asset plugin via your `composer.json` configuration: https://github.com/fxpio/composer-asset-plugin/blob/master/Resources/doc/index.md#disable-the-plugin

**Comment by samdark** [comment]
@SilverFire, @hiqsol how about putting ↑ at the website?

**Comment by hiqsol** [comment]
PR?

**Comment by and800** [comment]
@hiqsol gonna do it tonight
