### ISSUE TITLE
SSL certificate expired for https://asset-packagist.org/packages.json

### ISSUE THREAD

**Issue by suzit85** [hiqdev/asset-packagist#76]
### Please provide your `composer.json` if appropriate.
I am getting following error, because the ssl certificate is expired and not renewed. 

 The "https://asset-packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
  error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed                                                     
  Failed to enable crypto                                                                                                                  
  failed to open stream: operation failed   

------------------
On google chrome,  In certificate viewer,  the certificated is expired. It should have been renewed. 

Issued On	Monday, 9 October 2017 at 19:15:36
Expires On	Sunday, 7 January 2018 at 19:15:36

**Comment by rodrigoaguilera** [comment]
I think the certificate is renewed now

**Comment by suzit85** [comment]
Yes it is renewed.
