### ISSUE TITLE
Treat `peerDependencies` like `dependencies`

### ISSUE THREAD

**Issue by schmunk42** [hiqdev/asset-packagist#77]
Installing `jquery-contextmenu` from https://github.com/swisnl/jQuery-contextMenu/blob/master/package.json should also install jQuery, but it's listed as `peerDependencies`.

From my understanding they should be treated the same.

Example composer.json:

```
{
    "name": "root/app",
    "require": {
        "npm-asset/jquery-contextmenu": "^2.6"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}
```

**Comment by SilverFire** [comment]
https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies
