### ISSUE TITLE
Weird download link for version 2.3.4 of owl.carousel

### ISSUE THREAD

**Issue by rodrigoaguilera** [hiqdev/asset-packagist#80]
If you go to
https://asset-packagist.org/package/detail?fullname=npm-asset/owl.carousel
and try to download version 2.3.4 the link does not take you to the package.

On composer trying to install I get
[InvalidArgumentException]
Unknown downloader type: npm-signature. Available types: git, svn, fossil, hg, perforce, zip, rar, tar, gzip, xz, phar, file, path

**Comment by SamMousa** [comment]
This is causing the issue:

https://blog.npmjs.org/post/172999548390/new-pgp-machinery

**Comment by hiqsol** [comment]
Yep. Here is more: https://github.com/fxpio/composer-asset-plugin/issues/321

**Comment by webmaster777** [comment]
This is gonna be a real problem soon, as new versions of npm packages get published. 

We cannot get the latest version of codemirror for example: https://asset-packagist.org/package/npm-asset/codemirror

The ZIP url is malformed and results in a [404](https://asset-packagist.org/package/npm-asset/-----BEGIN%20PGP%20SIGNATURE-----Version:%20OpenPGP.js%20v3.0.4Comment:%20https://openpgpjs.orgwsFcBAEBCAAQBQJa2bUCCRA9TVsSAnZWagAAjMUP/1BVmjW8faXYcFISyZHPo/6q5iGwqJ8yx0Gpaasik6d+0ZF8+QJaoiBWTm0wRasrrPh1ZAvOqDUTAWcEzRqCdOxvIUOag1FJ0UvmwyIdhu0jRMOOBs4oGMyaSc6zh1JlYDtvqtpFcdvTpVdBEtQoSvzItur2Fpi4sAUTxKCTRJBvB3CS8TIRJlGkauEfg3Dax0qEgmTcDILhAnH4ayYep/qCdMw2JyAoCrwMHJNFvvGTNGv0eWQ0kwIDg+d2Hc9HGyizTI3zxdysqB+YUCjaNVjpagAOoTBYgXvPQ0xRoM6fvtA1zQPvt95DD0GQXhKm7QZ0WVG7Gh2irJ+ni+Lt7wDtJTEKHyf/eCBsVCPBY6Jdwc5NAXvfJmflmgKzuP3p+WZiZj7x6LPE8WPQdEGL0NQ/pogv/YbXgLPMRSxLVEd9SsSdMzTUR4XWvYyAKDK36L4h2yICPykrEbXwKhpSoxpFvqM8uK/T6Pj8t3Z4iIrNMT3Vk7OwYpXZfXs7sUJDzAGA+k1JWL8Qa1AnDhMdZy1kkDX7gp60JlD4+2Ix9GNZDDOUMCu2IIUd2Yec/LvW/gYNc5dKEwKnnqKFxN1KaxE3CKjUGT18i5c/DOHdYMrlwN15nqSADyPS5lPeJ0ZrZL4vUgeRsllOHoqMxyAAAiOc1jK7N83H7iu31e+PlMAy=nrga-----END%20PGP%20SIGNATURE-----).

While composer automatically tries to install the new version it will result in an error every time I run `composer update`:

~~~
> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                                              
Package operations: 0 installs, 8 updates, 0 removals
  - Removing npm-asset/codemirror (5.36.0)

                                                                                                                                       
  [InvalidArgumentException]                                                                                                           
  Unknown downloader type: npm-signature. Available types: git, svn, fossil, hg, perforce, zip, rar, tar, gzip, xz, phar, file, path.  
                                                                                                                                       

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

~~~

**Comment by SamMousa** [comment]
@hiqsol are you working on this? If not, will you have time or should we try to make a PR?

**Comment by hiqsol** [comment]
Actually I thought the problem is going to be solved in composer-asset-plugin.
I've seen discussion https://github.com/fxpio/composer-asset-plugin/issues/321 and corresponding PR there: https://github.com/fxpio/composer-asset-plugin/pull/323
If the problem is solved there then it's solved here automatically.

**Comment by hiqsol** [comment]
I need to update (check everything still works).
It takes some time.

**Comment by hiqsol** [comment]
Done update. Looks fine.

Troublesome packages need to be updated (refetched from npm) to become usable.
So I updated all the packages mentioned in issues.

All the available packages will be updated automatically. But it will take some days, so if you still come across this error (`Unknown downloader type`), please update corresponding package manually with pressing 'Fetch updates from Npm' button on asset-packagist.org

In case you don't know which package causes the problem please use `composer update -v' it provides more information. Look for lines like this:
```
Package operations: 13 install, 0 updates, 0 removals
Installs: npm-asset/ajv-keywords:3.2.0, npm-asset/punycode:v2.1.1, npm-asset/uri-js:4.2.1, npm-asset/fast-deep-equal:2.0.1, npm-asset/ajv:6.5.0, npm-asset/schema-utils:0.4.5, npm-asset/json5:0.5.1, npm-asset/emojis-list:2.1.0, npm-asset/big.js:3.2.0, npm-asset/loader-utils:1.1.0, npm-asset/worker-loader:1.1.1, npm-asset/node-ensure:0.0.0, npm-asset/pdfjs-dist:2.0.489
```
