### ISSUE TITLE
cant install assets npm

### ISSUE THREAD

**Issue by daunt** [hiqdev/asset-packagist#83]
### Please provide your `composer.json` if appropriate.
[485.3MB/49.81s] Package operations: 8 installs, 0 updates, 0 removals
[485.3MB/49.81s] Installs: npm-asset/metismenu:2.7.7, npm-asset/owl.carousel:2.3.4, npm-asset/escape-html:1.0.3, npm-asset/shaven:0.8.1, npm-asset/holderjs:2.9.4, npm-asset/idle-timer:1.2.0, bower-asset/jquery-idletimer:1.0.2, npm-asset/tinymce:4.7.12

  [InvalidArgumentException]
  Unknown downloader type: npm-signature. Available types: git, svn, fossil, hg, perforce, zip, rar, tar, gzip, xz, phar, file, path.

Exception trace:
 () at phar://C:/composer/composer.phar/src/Composer/Downloader/DownloadManager.php:128
 Composer\Downloader\DownloadManager->getDownloader() at phar://C:/composer/composer.phar/src/Composer/Downloader/DownloadManager.php:152
 Composer\Downloader\DownloadManager->getDownloaderForInstalledPackage() at phar://C:/composer/composer.phar/src/Composer/Downloader/DownloadManager.php:211
 Composer\Downloader\DownloadManager->download() at phar://C:/composer/composer.phar/src/Composer/Installer/LibraryInstaller.php:197
 Composer\Installer\LibraryInstaller->installCode() at phar://C:/composer/composer.phar/src/Composer/Installer/LibraryInstaller.php:101
 Composer\Installer\LibraryInstaller->install() at phar://C:/composer/composer.phar/src/Composer/Installer/InstallationManager.php:173
 Composer\Installer\InstallationManager->install() at phar://C:/composer/composer.phar/src/Composer/Installer/InstallationManager.php:160
 Composer\Installer\InstallationManager->execute() at phar://C:/composer/composer.phar/src/Composer/Installer.php:589
 Composer\Installer->doInstall() at phar://C:/composer/composer.phar/src/Composer/Installer.php:228
 Composer\Installer->run() at phar://C:/composer/composer.phar/src/Composer/Command/UpdateCommand.php:161
 Composer\Command\UpdateCommand->execute() at phar://C:/composer/composer.phar/vendor/symfony/console/Command/Command.php:242
 Symfony\Component\Console\Command\Command->run() at phar://C:/composer/composer.phar/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/composer/composer.phar/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar://C:/composer/composer.phar/src/Composer/Console/Application.php:251
 Composer\Console\Application->doRun() at phar://C:/composer/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar://C:/composer/composer.phar/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar://C:/composer/composer.phar/bin/composer:59
 require() at C:\composer\composer.phar:24

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by xorti** [comment]
I'm also having this issue:

```
> composer require npm-asset/pdfjs-dist
Using version ^2.0 for npm-asset/pdfjs-dist
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 15 installs, 0 updates, 0 removals
  - Installing npm-asset/json-schema-traverse (0.3.1): Loading from cache
  - Installing npm-asset/fast-json-stable-stringify (2.0.0): Loading from cache


  [InvalidArgumentException]
  Unknown downloader type: npm-signature. Available types: git, svn, fossil, hg, perforce, zip, rar, tar, gzip, xz, phar, file, path.


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
```
