### ISSUE TITLE
some npm-assets are broken lately by "Unknown downloader type: npm-signature" error

### ISSUE THREAD

**Issue by swayok** [hiqdev/asset-packagist#85]
Here is what i have in console:

Updates: npm-asset/bootstrap-select:1.13.1, npm-asset/moment:2.22.1, npm-asset/bootstrap-fileinput:4.4.8, npm-asset/ionicons:4.1.2
  - Removing npm-asset/bootstrap-select (1.12.4)

[InvalidArgumentException]                                                   
  Unknown downloader type: npm-signature. Available types: git, svn, fossil,   
  hg, perforce, zip, rar, tar, gzip, xz, phar, file, path.                     
                                                                               
Exception trace:
 () at phar://E:/OpenServer/modules/php/PHP-7.1-x64/composer.phar/src/Composer/Downloader/DownloadManager.php:128
 Composer\Downloader\DownloadManager->getDownloader() at phar://E:/OpenServer/modules/php/PHP-7.1-x64/composer.phar/src/Composer/Downloader/DownloadManager.php:152

Same issue happens for fxpio/composer-asset-plugin but some people say it was solved. Also I do not have fxpio/composer-asset-plugin installed

**Comment by vinpel** [comment]
fxpio issue : https://github.com/fxpio/composer-asset-plugin/issues/321

the root of the change : https://blog.npmjs.org/post/172999548390/new-pgp-machinery

**Comment by hiqsol** [comment]
See #80
