### ISSUE TITLE
npm-asset/babel-cli

### ISSUE THREAD

**Issue by Faboslav** [hiqdev/asset-packagist#86]
I can not install babel-cli due to some dep. problems.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - npm-asset/babel-runtime 6.26.0 requires npm-asset/regenerator-runtime >=0.11.0,<0.12.0 -> satisfiable by npm-asset/regenerator-runtime[0.11.1, 0.11.0].
    - Can only install one of: npm-asset/regenerator-runtime[0.10.5, 0.11.1].
    - Can only install one of: npm-asset/regenerator-runtime[0.10.5, 0.11.0].
    - npm-asset/babel-polyfill 6.26.0 requires npm-asset/regenerator-runtime >=0.10.5,<0.11.0 -> satisfiable by npm-asset/regenerator-runtime[0.10.5].
    - npm-asset/babel-cli 6.26.0 requires npm-asset/babel-polyfill >=6.26.0,<7.0.0 -> satisfiable by npm-asset/babel-polyfill[6.26.0].
    - npm-asset/babel-cli 6.26.0 requires npm-asset/babel-runtime >=6.26.0,<7.0.0 -> satisfiable by npm-asset/babel-runtime[6.26.0].
    - Installation request for npm-asset/babel-cli ^6.26 -> satisfiable by npm-asset/babel-cli[6.26.0].

**Comment by hiqsol** [comment]
Sorry at the moment I don't know how to fix the problem.
Looks like babel-cli dependencies constraints are unresolvable for composer.
