### ISSUE TITLE
Package not view after publish npm.

### ISSUE THREAD

**Issue by eduavila** [hiqdev/asset-packagist#91]
Package npm is not found after posting. it is not possible to find a search, also in composer require.

https://www.npmjs.com/package/@coder-lrv/ndatatables

**Comment by rodrigoaguilera** [comment]
With "normal" npm packages you had to visit the url first to fetch the package. Example
https://asset-packagist.org/package/npm-asset/datatables

But with the @username part I don't know how to make those packages available

**Comment by rodrigoaguilera** [comment]
Oh, I just found the info on https://asset-packagist.org/

you need to use '--' like this:

https://asset-packagist.org/package/npm-asset/coder-lrv--ndatatables

**Comment by eduavila** [comment]
It worked. Thank you.
