### ISSUE TITLE
Couldn't find new npm-asset

### ISSUE THREAD

**Issue by ivankff** [hiqdev/asset-packagist#92]
Hello.

I couldn't find that new package
https://www.npmjs.com/package/ivankff-scss-mixin
which had been created one day before.

So I couldn't install it into my project by composer:
"npm-asset/ivankff-scss-mixin": "~1.0.0"

**Comment by rodrigoaguilera** [comment]
You need to visit
https://asset-packagist.org/package/npm-asset/ivankff-scss-mixin

@hiqsol Is this 'trick' somewhere in the docs? I can't find it

**Comment by ivankff** [comment]
It works! Thank you.

**Comment by hiqsol** [comment]
@rodrigoaguilera 

This?

![a8u-kvwxq_mmuv5j-lpbmq](https://user-images.githubusercontent.com/11820365/46474239-05011880-c7eb-11e8-85ae-53ce180da727.png)

**Comment by ivankff** [comment]
This package isn't found by search at the top of page

If you follow this link, you'll see "No results found." now
https://asset-packagist.org/package/search?query=ivankff-scss-mixin&platform=bower%2Cnpm

**Comment by hiqsol** [comment]
Oh, sorry. I've asked wrong question.

Yes. It's not documented.

**Comment by hiqsol** [comment]
The packages search is implemented using https://libraries.io/ service.
I think your package could not be found yet because the service has some delay.

**Comment by ivankff** [comment]
Thank you very much!
I've got it
