### ISSUE TITLE
Is it possible to point asset-packagist to a private npm registry ?

### ISSUE THREAD

**Issue by CaptainQuirk** [hiqdev/asset-packagist#98]
Hi there,

As mentioned in the issue title, can one make `asset-packagist` point to a private npm registry ? 

Thanks !

**Comment by hiqsol** [comment]
No, I think it's out of our scope.

I'm not sure but it seems to me that the simplest solution could be adding git repository to composer.json:

https://getcomposer.org/doc/05-repositories.md#vcs
